version: "3"

services:
  mongobackend:
    image: mongo:7.0.7-jammy
    restart: unless-stopped    
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongobackend
    image: calderonperaza/ejemplobackend:latest
    #build:
    #  context: .      
    restart: unless-stopped    
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongobackend:27017/ejemplo
      
volumes:
  db:
#para iniciar usa el comando
#sudo docker compose up -d
#para detener
#sudo docker compose down
#para obligar a compilar de nuevo
#sudo docker compose up -d --build